# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Client

# Model Form Field configuration
form: $/albrightlabs/client/models/client/fields.yaml

# Model Class name
modelClass: AlbrightLabs\Client\Models\Client

# Default redirect location
defaultRedirect: albrightlabs/client/clients

# Create page
create:
    title: Create Client
    redirect: albrightlabs/client/clients/preview/:id
    redirectClose: albrightlabs/client/clients

# Update page
update:
    title: Edit Client
    redirect: albrightlabs/client/clients/preview/:id
    redirectClose: albrightlabs/client/clients

# Preview page
preview:
    title: Preview Client
